name: Cypress E2E Tests

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Create .env file with secrets (if your Cypress reads from it)
      - name: Create .env file
        run: |
          echo "KEYCLOAK_USERNAME=${{ secrets.KEYCLOAK_USERNAME }}" > .env
          echo "KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }}" >> .env
      # 5️⃣ Run Cypress tests (all specs) and capture log
      - name: Run Cypress tests (headless)
        run: |
          # Stream output to the job logs and save to cypress-run.log for artifact upload
          npx cypress run 2>&1 | tee cypress-run.log

      # 6️⃣ Upload the captured Cypress run log so you can download it from the run
      - name: Upload Cypress run log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-run-log
          path: cypress-run.log
